{
 "title": "ft_transcendence",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(websocket_connected_users)\n",
     "legendFormat": "active_users"
    }
   ]
  },
  {
   "title": "Services uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (active_games{status=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (active_games{status=\"waiting\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed attempt login admin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(failed_login_attempts_total{username=\"admin\"}[5m]))",
     "legendFormat": "{{active_user}}"
    }
   ]
  },
  {
   "title": "Failed attempt login in last 5m",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(failed_login_attempts_total[5m]))",
     "legendFormat": "{{active_user}}"
    }
   ]
  },
  {
   "title": "Ongoing Tournaments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_tournaments{status=\"ongoing\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Tournaments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(active_tournaments{status=\"pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed attempt on login account in last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "increase(failed_login_attempts_total[5m])",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Request nginx per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[$__rate_interval]))",
     "legendFormat": "Request nginx per second in last minute"
    }
   ]
  },
  {
   "title": "requests services per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx - Dropped Connections/s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[1m]) - rate(nginx_connections_handled[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx - Connections Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nginx_connections_waiting", "legendFormat": "waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" }
   ]
  },
  {
   "title": " Nginx - Active Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of method request in last minutes",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total[1m]))\n",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum by (method) (\n  increase(http_requests_total[1m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors 5xx rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (job) (\n  rate(http_requests_total{status_code=~\"5..\"}[5m]) \n  or \n  (rate(http_requests_total[5m]) * 0)\n)\n/\nsum by (job) (rate(http_requests_total[5m]))\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of 5xx errors in last 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status_code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Users in last 5 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(successful_login_attempts_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time - P95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_response_time_seconds_bucket{status_code!=\"404\"}[5m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Social request time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (route) (avg_over_time(http_response_time_seconds_sum{job=\"social\", status_code!=\"404\"}[$__interval]))\n/\nsum by (route) (avg_over_time(http_response_time_seconds_count{job=\"social\", status_code!=\"404\"}[$__interval]))",
     "legendFormat": " {{route}}"
    }
   ]
  },
  {
   "title": "Users request time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (route) (avg_over_time(http_response_time_seconds_sum{job=\"users\", status_code!=\"404\"}[$__interval]))\n/\nsum by (route) (avg_over_time(http_response_time_seconds_count{job=\"users\", status_code!=\"404\"}[$__interval]))",
     "legendFormat": " {{route}}"
    }
   ]
  },
  {
   "title": "Game request time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (route) (avg_over_time(http_response_time_seconds_sum{job=\"game\", status_code!=\"404\"}[$__interval]))\n/\nsum by (route) (avg_over_time(http_response_time_seconds_count{job=\"game\", status_code!=\"404\"}[$__interval]))",
     "legendFormat": " {{route}}"
    }
   ]
  },
  {
   "title": "Auth request time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (route) (avg_over_time(http_response_time_seconds_sum{job=\"auth\", status_code!=\"404\"}[$__interval]))\n/\nsum by (route) (avg_over_time(http_response_time_seconds_count{job=\"auth\", status_code!=\"404\"}[$__interval]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "2fa request time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (route) (avg_over_time(http_response_time_seconds_sum{job=\"2fa\", status_code!=\"404\"}[$__interval]))\n/\nsum by (route) (avg_over_time(http_response_time_seconds_count{job=\"2fa\", status_code!=\"404\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_mean_seconds * 1000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU usage (cores %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Growth (10min %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(delta(nodejs_heap_size_used_bytes[10m]) / nodejs_heap_size_used_bytes) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}