#!/usr/bin/ruby

commit_message = File.read(ARGV[0])
pattern = /^(?:wip|feat|fix|build|ci|docs|perf|refactor|style|test|revert|chore)(?:\(\S+\))?:.{0,50}$(?:\n\n^.{0,100}$){0,2}(?:\n#.*|\n)*|^(?:Merge|Revert).*(?:\n#.*|\n)*/

unless commit_message.match?(pattern)
  puts "Invalid commit message format."
  puts "See: https://github.com/anais-f/42_ft_transcendence/wiki/Git-conventions#commit-convention"
  puts commit_message
  exit 1
end

