FROM node:22-alpine AS build-packages

FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages/*/package*.json ./packages/
COPY services/*/app/package*.json ./services/*/app/

CMD ["npm", "run", "dev", "--workspace=services/pong-server/app"]
