FROM node:22-alpine

RUN apk add --no-cache libc6-compat python3 make g++ sqlite-dev

WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages/*/package*.json ./packages/
COPY services/*/app/package*.json ./services/*/app/

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=services/users/app"]
