FROM node:20-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages/*/package*.json ./packages/
COPY services/*/app/package*.json ./services/*/app/

EXPOSE 3042

CMD ["npm", "run", "dev", "--workspace=services/users/app"]
